Blogger/Models/Comentario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Blogger.Models
{
    public class Comentario
    {
        [Key]
        public int Id { get; set; }      
        [Required(ErrorMessage ="Comentário não pode ser vazio")]
        [StringLength(500)]
        public string Descricao { get; set; }
        [Required]
        [StringLength(50)]
        public string Autor { get; set; }
        public DateTime Data { get; set; }

        [ForeignKey("PublicacaoId")]
        public int PublicacaoId { get; set; }
        public Publicacao Publicacao { get; set; }

        public Usuario Usuario { get; set; }
        [ForeignKey("UsuarioId")]

        public int? UsuarioId { get; set; }

    }
}

Blogger/Controllers/ComentarioController.cs
using Blogger.Models.ViewModels;
using Blogger.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blogger.Controllers
{
    public class ComentarioController : Controller
    {
        private readonly IComentarioRepository _comentarioRepository;

        public ComentarioController(IComentarioRepository comentarioRepository)
        {
            _comentarioRepository = comentarioRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Criar(CadastrarComentarioViewModel comentarioVM)
        {
            if(ModelState.IsValid)
                await _comentarioRepository.Criar(comentarioVM);

            return RedirectToAction("Detalhes", "Publicacao", new { id = comentarioVM.PublicacaoId });

        }
    }
}

Blogger/Views/Comentario/_Cadastrar.cshtml
@using Blogger.Models.ViewModels
@model CadastrarComentarioViewModel

<div>
    <form asp-action="Criar" asp-controller="Comentario" method="post">
        <input hidden asp-for="PublicacaoId"/>
        <span asp-validation-for="Descricao" class="text-danger"></span>
        <div class="">       
            <textarea maxlength="500" asp-for="Descricao" type="text" class="form-control" aria-label="With textarea" placeholder="Adicione um comentário..."></textarea>
            <div class="d-flex justify-content-end">
                <button class="btn btn-outline-dark mt-2" type="submit">Comentar</button>
            </div>
        </div>      
    </form>
</div>